### ISSUE TITLE
lack branch for riscv64 android 12

### ISSUE THREAD

**Issue by unicornx** [riscv-android-src/platform-tools-tradefederation#1]
We need a branch for riscv64 android 12.
And we also need a new repo for https://android.googlesource.com/platform/tools/tradefederation/prebuilts/ which contains prebuilt binaries to support riscv64.

Currently, when we make cts and run cts cases, will report error such as below:
```
07-04 12:01:40 E/TestInvocation: Unexpected exception when running invocation: java.lang.IllegalArgumentException: None of the abi supported by this tests suite build ('[arm64-v8a, armeabi-v7a, x86_64, x86, mips64, mips]') are supported by the device ('[riscv64]').
07-04 12:01:40 E/TestInvocation: None of the abi supported by this tests suite build ('[arm64-v8a, armeabi-v7a, x86_64, x86, mips64, mips]') are supported by the device ('[riscv64]').
java.lang.IllegalArgumentException: None of the abi supported by this tests suite build ('[arm64-v8a, armeabi-v7a, x86_64, x86, mips64, mips]') are supported by the device ('[riscv64]').
        at com.android.tradefed.testtype.suite.ITestSuite.getAbis(ITestSuite.java:1321)
        at com.android.tradefed.testtype.suite.BaseTestSuite.loadTests(BaseTestSuite.java:239)
        at com.android.compatibility.common.tradefed.testtype.suite.CompatibilityTestSuite.loadTests(CompatibilityTestSuite.java:109)
        at com.android.tradefed.testtype.suite.ITestSuite.loadAndFilter(ITestSuite.java:416)
        at com.android.tradefed.testtype.suite.ITestSuite.createExecutionList(ITestSuite.java:517)
        at com.android.tradefed.testtype.suite.ITestSuite.run(ITestSuite.java:655)
        at com.android.tradefed.invoker.InvocationExecution.runTest(InvocationExecution.java:880)
        at com.android.tradefed.invoker.InvocationExecution.runTests(InvocationExecution.java:705)
        at com.android.tradefed.invoker.TestInvocation.prepareAndRun(TestInvocation.java:483)
        at com.android.tradefed.invoker.TestInvocation.performInvocation(TestInvocation.java:252)
        at com.android.tradefed.invoker.TestInvocation.invoke(TestInvocation.java:1107)
        at com.android.tradefed.command.CommandScheduler$InvocationThread.run(CommandScheduler.java:631)

```

**Comment by unicornx** [comment]
https://github.com/riscv-android-src/platform-tools-tradefederation/tree/riscv64-android-12.0.0_dev was created.

and manifest was changed with https://github.com/riscv-android-src/manifest/commit/e07293e3267334a6c397306614cd28a2ff357b66 to add tradefederation modules for xts.

Note: aosp 12 preview uses tools/tradefederation/core and tools/tradefederation/contrib so we can update it easily. Will use tools/tradefederation/prebuilts after offiically releasing.
